---
- hosts: localhost
  become: true
  tasks:
  - name: Install Azure CLI
    command: "{{ item }}"
    with_items:
      - sudo yum check-update
      - sudo yum install -y gcc libffi-devel python-devel openssl-devel epel-release
      - sudo yum install -y python-pip python-wheel
      - sudo pip install ansible[azure]
    
