---
- hosts: all:!10.1.150.111
  become: true
  tasks:
  - name: updating the tags
    shell: "az vm update --resource-group Sempra-terraform-RG --name tf-LINUX-vm --set tags.environment=development"
