---
- hosts: all:!10.1.150.111
  become: true
  tasks:
  - name: updating the tags
    command: "az vm update --resource-group Remote-exec-terraform-RG  --name Remote-tf-LINUX-vm --set tags.environment=development"
